import styles from "./iconSettings.module.css";
export default function IconSettings() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30">
      <g>
        <line
          vectorEffect="non-scaling-stroke"
          className={styles.cls1}
          x1="7.55"
          y1="5.55"
          x2="7.55"
          y2="24.55"
        />
        <line
          vectorEffect="non-scaling-stroke"
          className={styles.cls1}
          x1="12.55"
          y1="5.55"
          x2="12.55"
          y2="24.55"
        />
        <line
          vectorEffect="non-scaling-stroke"
          className={styles.cls1}
          x1="17.55"
          y1="5.55"
          x2="17.55"
          y2="24.55"
        />
        <line
          vectorEffect="non-scaling-stroke"
          className={styles.cls1}
          x1="22.55"
          y1="5.55"
          x2="22.55"
          y2="24.55"
        />
      </g>
      <circle
        vectorEffect="non-scaling-stroke"
        className={styles.cls2}
        cx="7.55"
        cy="10.96"
        r="1.5"
      />
      <circle
        vectorEffect="non-scaling-stroke"
        className={styles.cls2}
        cx="22.55"
        cy="11.73"
        r="1.5"
      />
      <circle
        vectorEffect="non-scaling-stroke"
        className={styles.cls2}
        cx="17.55"
        cy="16.29"
        r="1.5"
      />
      <circle
        vectorEffect="non-scaling-stroke"
        className={styles.cls2}
        cx="12.55"
        cy="16.29"
        r="1.5"
      />
    </svg>
  );
}
